from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

import pandas as pd

from eyetap_analysis.agreement import (
    agreement_results_to_frame,
    compute_agreement_by_group,
    summarize_cohort_agreement,
)
from eyetap_analysis.config import load_config
from eyetap_analysis.dtype import AnalyticsDetails
from eyetap_analysis.efficiency import (
    compute_session_efficiency,
    summarize_cohort_efficiency,
    summarize_reading_session_efficiency,
)
from eyetap_analysis.load import (
    load_analytics,
    load_annotations,
    load_session_metadata,
    analytics_to_df,
)
from eyetap_analysis.report import write_analysis_outputs, write_validation_report
from eyetap_analysis.stats import (
    compare_efficiency_across_cohorts,
    summarize_agreement_with_ci,
)


def _parse_cohort_overrides(raw: list[str] | None) -> dict[str, Path]:
    overrides: dict[str, Path] = {}
    if not raw:
        return overrides
    for item in raw:
        name, path = item.split("=", maxsplit=1)
        overrides[name.strip()] = Path(path.strip())
    return overrides


def run_analysis(
    config_path: Path,
    output_dir: Path,
    association_path: str = "./data/association.csv",
    text_association_path: str = "./data/text-association.csv",
    userdata_path: str | None = None,
    cohort_overrides: dict[str, Path] | None = None,
) -> int:
    config = load_config(
        config_path,
        userdata_path_override=userdata_path,
        cohort_overrides=cohort_overrides or {},
    )
    # Columns: user_id, cohort, survey_id
    association = pd.read_csv(association_path)
    text_association = pd.read_csv(text_association_path)
    annotations, validation = load_annotations(config)
    analytics: AnalyticsDetails = load_analytics(config.userdata)

    for user in analytics["raw"]:
        print(
            "The session of user",
            user,
            "is split into",
            len(analytics["raw"][user]) - 1,
            "parts (text changes)",
        )
    analytics_df = analytics_to_df(analytics, association)
    output_dir.mkdir(parents=True, exist_ok=True)
    if not validation.ok or annotations.empty:
        write_validation_report(validation, output_dir)
        return 1

    session_efficiency = compute_session_efficiency(analytics_df)
    cohort_efficiency_summary = pd.DataFrame() # summarize_cohort_efficiency(session_efficiency)
    reading_session_efficiency = pd.DataFrame() # summarize_reading_session_efficiency(session_efficiency)

    agreement_results = compute_agreement_by_group(annotations, config)
    agreement_by_reading_session = agreement_results_to_frame(agreement_results)
    cohort_agreement_summary = summarize_cohort_agreement(agreement_by_reading_session)
    cohort_agreement_ci = summarize_agreement_with_ci(agreement_by_reading_session)

    efficiency_tests, efficiency_pairwise = pd.DataFrame(), pd.DataFrame() # compare_efficiency_across_cohorts(session_efficiency)

    outputs = write_analysis_outputs(
        output_dir,
        validation_report=validation,
        session_efficiency=session_efficiency,
        cohort_efficiency_summary=cohort_efficiency_summary,
        reading_session_efficiency=reading_session_efficiency,
        agreement_by_reading_session=agreement_by_reading_session,
        cohort_agreement_summary=cohort_agreement_summary,
        cohort_agreement_ci=cohort_agreement_ci,
        efficiency_tests=efficiency_tests,
        efficiency_pairwise=efficiency_pairwise,
    )

    print(f"Analysis complete. Outputs written to {output_dir}")
    for name, path in outputs.items():
        if path is not None:
            print(f"  - {name}")

    # print("\nSession annotation counts:")
    # print(
    #     session_efficiency[["cohort", "ANNOTATIONSESSIONID", "annotation_count"]]
    #     .sort_values(["cohort", "ANNOTATIONSESSIONID"])
    #     .to_string(index=False)
    # )

    if validation.warnings:
        print("\nWarnings:")
        for warning in validation.warnings:
            print(f"  - {warning}")

    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run eyetracking annotation survey analysis"
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("config.yaml"),
        help="Path to config.yaml",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory (default: outputs/run_<today>/)",
    )
    parser.add_argument(
        "--cohort-file",
        action="append",
        default=[],
        metavar="NAME=PATH",
        help="Override cohort CSV path, e.g. cohort1=data/cohort1.csv",
    )
    parser.add_argument(
        "--userdata-file",
        default="data/userdata.csv",
        help="Path to userdata file, as generated by the script",
    )
    parser.add_argument(
        "--association-file",
        default="data/association.csv",
        help="Path to association file, as generated by the script",
    )
    parser.add_argument(
        "--text-association-file",
        default="data/text-association.csv",
        help="Path to text association file, as generated by the script",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    config_path = args.config.resolve()
    overrides = _parse_cohort_overrides(args.cohort_file)

    output_dir = args.output
    if output_dir is None:
        output_dir = Path("outputs") / f"run_{date.today().isoformat()}"
    output_dir = output_dir.resolve()

    return run_analysis(config_path, output_dir, args.association_file, args.text_association_file, args.userdata_file, overrides or None)


if __name__ == "__main__":
    raise SystemExit(main())
